### PR TITLE
Minor additions for ProLiant redfish fw

### PR DESCRIPTION
**Pull request by dan-bryant**
Made some additions for smoother execution against ProLiant redfish fw:
1. Added scripts to build / run with cert-store creation.  Getting the certs lined up can be laborious.
2. Added BasicAuth capabilities authenticated SSL based GETs.
3. Added support for compressed (Gziip) content on HTTPS response.
4. Tightened the URL parsing to avoid redirects

Note... I didn't add full support for 3xx redirects.  This will likely want to be addressed eventually, but I wanted to have a small change deck for this pull request.

### CODE REVIEW

**Comment by hankbr** [comment]
Dan, I don't see anything HP specific except the copyright statements. Is it ok if I change the commit comment to more like your list of changes? I propose your words...
Added BasicAuth capabilities authenticated SSL based GETs.

**Comment by dan-bryant** [comment]
Of course

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by dan-bryant** [comment]
@hankbr , just occurred to me that the compressed content support I put in was rather one directional.  It should actually check the content to determine if it is compressed or not before making that assumption.  I'll play around with it and see if there is an easy way to check the headers before parsing the content.  I'm not sure if Olingo makes those actions (GET -vs- parse) atomic or not.

**Comment by hankbr** [comment]
danhp,
I'm not sure about the compressed content either.
Read the ReadMe on the master. I changed the mave projects around and
renamed the class with the mail method where you added the https, port and
host names.
look at
https://github.com/RedHelixOrg/RedHelix-1/blob/master/doc/dev-status.md

It might save you time if you clone the master and start from there.
Hankbr

**Pull request merged**
